extern unsigned char uc_x;
extern unsigned char uc_y;
extern unsigned char uc_z;
extern char sc_x;
extern char sc_y;
extern char sc_z;
extern unsigned short us_x;
extern unsigned short us_y;
extern unsigned short us_z;
extern short ss_x;
extern short ss_y;
extern short ss_z;
extern long sl_x;
extern long sl_y;
extern unsigned long ul_x;
extern unsigned long ul_y;

void set_uc_x (unsigned char x);
void set_uc_y (unsigned char y);
void set_sc_x (char x);
void set_sc_y (char y);
void set_us_x (unsigned short x);
void set_us_y (unsigned short y);
void set_ss_x (short x);
void set_ss_y (short y);
void set_ul_x (unsigned long x);
void set_ul_y (unsigned long y);
void set_sl_x (long x);
void set_sl_y (long y);
