/*
 *  More comprehensive tests for 16-bit multiple and divide ops.  C99 standard
 *  https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1124.pdf section 6.5.5
 *  states (a/b)*b+a%b == a which implies result of a modulo operation with
 *  negative dividend is itself negative.
 */

#include "tap.h"

typedef struct
{
    int a;
    int b;

    int mul;    /* a * b */
    int div;    /* a / b */
    int mod;    /* a % b */
} testcase_t;

/*  This table was generated by chatGPT */

static const testcase_t cases[] =
{
    /* trivial */
    {      1,      1,      1,      1,    0 },
    {     -1,      1,     -1,     -1,    0 },
    {      1,     -1,     -1,     -1,    0 },
    {     -1,     -1,      1,      1,    0 },

    /* small positive */
    {      7,      3,     21,      2,    1 },
    {     15,      4,     60,      3,    3 },
    {     57,     11,    627,      5,    2 },
    {    127,      7,    889,     18,    1 },

    /* small negative combinations */
    {     -7,      3,    -21,     -2,   -1 },
    {      7,     -3,    -21,     -2,    1 },
    {     -7,     -3,     21,      2,   -1 },

    {   -127,      7,   -889,    -18,   -1 },
    {    127,     -7,   -889,    -18,    1 },
    {   -127,     -7,    889,     18,   -1 },

    /* powers of two */
    {    128,      2,    256,     64,    0 },
    {    256,      8,   2048,     32,    0 },
    {    512,     16,   8192,     32,    0 },
    {   1024,     32, -32768,     32,    0 },
    {  -1024,     32, -32768,    -32,    0 },

    /* two-byte values */
    {    479,     57,  27303,      8,   23 },
    {   -479,     57, -27303,     -8,  -23 },
    {    479,    -57, -27303,     -8,   23 },
    {   -479,    -57,  27303,      8,  -23 },

    {   1023,     31,  31713,     33,    0 },
    {  -1023,     31, -31713,    -33,    0 },

    /* exact divisions */
    {   2046,     31,  -2110,     66,    0 },
    {  -2046,     31,   2110,    -66,    0 },

    {  16384,    128,      0,    128,    0 },
    { -16384,    128,      0,   -128,    0 },

    /* remainder = 1 */
    {   8191,    127,  -8319,     64,   63 },
    {  -8191,    127,   8319,    -64,  -63 },

    /* quotient zero */
    {      5,    127,    635,      0,    5 },
    {     -5,    127,   -635,      0,   -5 },
    {      5,   -127,   -635,      0,    5 },
    {     -5,   -127,    635,      0,   -5 },

    /* near signed 16-bit product limit */
    {    181,    181,  32761,      1,    0 },
    {   -181,    181, -32761,     -1,    0 },
    {    255,    127,  32385,      2,    1 },
    {   -255,    127, -32385,     -2,   -1 },

    /* larger mixed values */
    {   4095,      7,  28665,    585,    0 },
    {  -4095,      7, -28665,   -585,    0 },

    {   3640,      9,  32760,    404,    4 },
    {  -3640,      9, -32760,   -404,   -4 },

    /* Edge / limit  test case.  This currently fails so has been commented out
    { -32768,  32767,  32768,   -1, -1 },
    */

    { -13, 5, -65, -2, -3 },
    { -13, -5, 65, 2, -3 }
};

#define TABLE_COUNT (sizeof(cases) / sizeof(cases[0]))

void t_i16_mul_table(void)
{
    for (unsigned i = 0; i < TABLE_COUNT; i++)
    {
	 if ( (cases[i].a * cases[i].b) != cases[i].mul)
		 test_printf ("%d * %d == %d should be %d\n",
				 cases[i].a, cases[i].b,
				 cases[i].a * cases[i].b,
				 cases[i].mul);

        test_execute(__func__,
                     (cases[i].a * cases[i].b)
                     == cases[i].mul);
    }
}
	
void t_i16_div_table(void)
{
    for (unsigned i = 0; i < TABLE_COUNT; i++)
    {
	 if ( (cases[i].a / cases[i].b) != cases[i].div)
		 test_printf ("%d / %d == %d should be %d\n",
				 cases[i].a, cases[i].b,
				 cases[i].a / cases[i].b,
				 cases[i].div);

        test_execute(__func__,
                     (cases[i].a / cases[i].b)
                     == cases[i].div);
    }
}
void t_i16_mod_table(void)
{
    for (unsigned i = 0; i < TABLE_COUNT; i++)
    {
	 if ( (cases[i].a % cases[i].b) != cases[i].mod)
		 test_printf ("%d %% %d == %d should be %d\n",
				 cases[i].a, cases[i].b,
				 cases[i].a % cases[i].b,
				 cases[i].mod);

        test_execute(__func__,
                     (cases[i].a % cases[i].b)
                     == cases[i].mod);
    }
}

#include "ltoa.c"

TESTFUNC tests[] = 
{
    t_i16_mul_table,
    t_i16_div_table,
    t_i16_mod_table
};

#define TEST_COUNT (sizeof (tests) / sizeof (TESTFUNC))

int main(void)
{
    test_run (tests, TEST_COUNT);

    return 0;
}
