all: elf2ea5 elf2cart ea5split

elf2ea5: elf2ea5.c
	gcc elf2ea5.c -o elf2ea5

elf2cart: elf2cart.c
	gcc elf2cart.c -o elf2cart

ea5split: ea5split.c
	gcc ea5split.c -o ea5split

clean:
	rm elf2ea5 elf2cart ea5split

